sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with docker"
  - docker build -t seanpeak-dev/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true seanpeak-dev/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success"
